import {describe,expect,it} from 'vitest';
import {animatedScenarios,scenePacks} from '../src/lessons';
import {timelineDuration} from '../src/logic/timeline';

describe('role-specific animation curriculum',()=>{
  it('contains the exact 50-scene first release',()=>{expect(animatedScenarios).toHaveLength(50);expect(Object.fromEntries(scenePacks.map((pack)=>[pack.id,pack.scenes.length]))).toEqual({winger:8,striker:8,'central-midfielder':8,fullback:6,'center-defender':6,goalkeeper:4,teamwork:10})});
  it('has no cloned curriculum signatures',()=>{expect(new Set(animatedScenarios.map((scene)=>`${scene.introNarration}|${scene.formalConcept}`)).size).toBe(50);const signatures=new Map<string,string[]>();for(const scene of animatedScenarios){const signature=JSON.stringify({actors:scene.actors.map((actor)=>actor.start),good:scene.results[0].animationSteps,poor:scene.results.at(-1)!.animationSteps});signatures.set(signature,[...(signatures.get(signature)??[]),scene.id])}const duplicates=[...signatures.values()].filter((ids)=>ids.length>1);expect(duplicates,JSON.stringify(duplicates)).toEqual([])});
  it('plays setup and consequence animations for every visual choice',()=>{for(const scene of animatedScenarios){expect(timelineDuration(scene.setupAnimation),scene.id).toBeGreaterThanOrEqual(3000);expect(scene.choices.length).toBeGreaterThanOrEqual(2);expect(scene.choices.length).toBeLessThanOrEqual(3);expect(scene.results).toHaveLength(scene.choices.length);for(const choice of scene.choices){expect(choice.previewAnimation.length).toBeGreaterThan(0);const consequence=scene.results.find((item)=>item.choiceId===choice.id);expect(consequence,`${scene.id}/${choice.id}`).toBeDefined();expect(timelineDuration(consequence!.animationSteps),`${scene.id}/${choice.id}`).toBeGreaterThanOrEqual(2500)}}});
  it('uses normalized coordinates and cartoon human actors',()=>{for(const scene of animatedScenarios){expect(scene.actors.some((actor)=>actor.name==='Nolan')).toBe(true);expect(scene.actors.length).toBeGreaterThanOrEqual(5);const points=[scene.ballStart,...scene.actors.map((actor)=>actor.start),...scene.setupAnimation.flatMap((item)=>[item.from,item.to].filter(Boolean)),...scene.results.flatMap((result)=>result.animationSteps.flatMap((item)=>[item.from,item.to].filter(Boolean)))];for(const point of points){expect(point!.x).toBeGreaterThanOrEqual(0);expect(point!.x).toBeLessThanOrEqual(100);expect(point!.y).toBeGreaterThanOrEqual(0);expect(point!.y).toBeLessThanOrEqual(64)}}});
  it('implements required role-specific content',()=>{const ids=new Set(animatedScenarios.map((scene)=>scene.id));for(const id of ['WNG-03','WNG-07','STR-04','STR-06','STR-07','CM-01','CM-03','CM-06','CM-07','FB-03','FB-04','CB-03','CB-05','CB-06','GK-01','GK-02','GK-03','GK-04'])expect(ids.has(id),id).toBe(true);const goalkeeperActions=new Set(scenePacks.find((pack)=>pack.id==='goalkeeper')!.scenes.flatMap((scene)=>scene.results.flatMap((result)=>result.animationSteps.map((item)=>item.action))));for(const action of ['set','dive','catch','parry','clear','pass'])expect(goalkeeperActions.has(action as never),action).toBe(true)});
  it('offers two acceptable choices in every role pack',()=>{for(const pack of scenePacks)expect(pack.scenes.some((scene)=>scene.results.filter((result)=>result.quality!=='poor').length>=2),pack.id).toBe(true)});
  it('always shoots toward the opponent goal',()=>{for(const scene of animatedScenarios)for(const result of scene.results)for(const shot of result.animationSteps.filter((item)=>item.action==='shoot')){const shooter=scene.actors.find((actor)=>actor.id===shot.actorId)!;const opponentKeeper=scene.actors.find((actor)=>actor.goalkeeper&&actor.team!==shooter.team);expect(opponentKeeper,`${scene.id}/${result.choiceId}`).toBeDefined();expect(Math.abs(shot.to!.x-opponentKeeper!.start.x),`${scene.id}/${result.choiceId}`).toBeLessThanOrEqual(8)}});
});
